import { WorkerScriptOptions } from '../types';

export function generateWorkerScript(options: WorkerScriptOptions): string {
  const {
    uuid,
    proxyIp,
    fallbackSite,
    enableSubEndpoint,
    enableDashboard,
    subTitle
  } = options;

  return `// =========================================================================
// Cloudflare Worker VLESS Serverless Node Script
// Generated by Cloudflare Worker VLESS Studio
// Protocol: VLESS over WebSocket + TLS / HTTP
// =========================================================================

import { connect } from 'cloudflare:sockets';

// Configuration Variables
const userID = '${uuid.trim()}';
const proxyIP = '${proxyIp.trim()}';
const fallbackSite = '${fallbackSite.trim() || 'www.bing.com'}';
const subTitle = '${subTitle.trim() || 'Cloudflare-VLESS-Node'}';

export default {
  /**
   * Main Fetch Handler
   * @param {Request} request
   * @param {Object} env
   * @param {Object} ctx
   * @returns {Promise<Response>}
   */
  async fetch(request, env, ctx) {
    try {
      const actualUserID = env.UUID || userID;
      const actualProxyIP = env.PROXYIP || proxyIP;
      const url = new URL(request.url);
      const upgradeHeader = request.headers.get('Upgrade');

      // 1. WebSocket VLESS Proxy Tunnel Handler
      if (upgradeHeader === 'websocket') {
        return await vlessOverWSHandler(request, actualUserID, actualProxyIP);
      }

      // 2. Subscription Endpoints (${enableSubEndpoint ? 'Enabled' : 'Disabled'})
      ${enableSubEndpoint ? `
      if (url.pathname === '/sub' || url.pathname === '/sub/' || url.searchParams.has('sub')) {
        const host = request.headers.get('Host') || url.hostname;
        const format = url.searchParams.get('format') || 'v2ray';
        const cleanIpParam = url.searchParams.get('ip') || host;

        const vlessLink = \`vless://\${actualUserID}@\${cleanIpParam}:443?encryption=none&security=tls&sni=\${host}&type=ws&host=\${host}&path=%2F#\${encodeURIComponent(subTitle)}\`;
        const vlessHttpLink = \`vless://\${actualUserID}@\${cleanIpParam}:80?encryption=none&security=none&type=ws&host=\${host}&path=%2F#\${encodeURIComponent(subTitle + '-HTTP-80')}\`;
        
        if (format === 'clash' || format === 'mihomo') {
          const clashYaml = \`proxies:
  - name: "\${subTitle}-TLS-443"
    type: vless
    server: \${cleanIpParam}
    port: 443
    uuid: \${actualUserID}
    cipher: none
    udp: true
    tls: true
    client-fingerprint: chrome
    skip-cert-verify: false
    servername: \${host}
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: \${host}
\`;
          return new Response(clashYaml, {
            headers: {
              'Content-Type': 'text/yaml; charset=utf-8',
              'Subscription-Userinfo': 'upload=0; download=0; total=1073741824000; expire=0'
            }
          });
        }

        // Return standard Base64 subscription
        const subContent = [vlessLink, vlessHttpLink].join('\\n');
        const encoded = btoa(unescape(encodeURIComponent(subContent)));

        return new Response(encoded, {
          headers: {
            'Content-Type': 'text/plain; charset=utf-8',
            'Subscription-Userinfo': 'upload=0; download=0; total=1073741824000; expire=0',
            'Profile-Update-Interval': '24'
          }
        });
      }
      ` : ''}

      // 3. Fallback / Camouflage Landing Page
      ${enableDashboard ? `
      if (url.pathname === '/' || url.pathname === '/info') {
        const host = request.headers.get('Host') || url.hostname;
        return new Response(
          \`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Edge Network Gateway</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #f8fafc; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; padding: 20px; }
    .card { background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 32px; max-width: 480px; text-align: center; box-shadow: 0 10px 25px -5px rgba(0,0,0,0.3); }
    h1 { font-size: 20px; margin: 0 0 12px; color: #38bdf8; }
    p { font-size: 14px; color: #94a3b8; line-height: 1.6; margin: 0 0 20px; }
    .status { display: inline-flex; align-items: center; gap: 8px; background: rgba(34, 197, 94, 0.1); border: 1px solid #22c55e; color: #4ade80; padding: 6px 14px; border-radius: 20px; font-size: 13px; font-weight: 500; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Cloudflare Edge Service</h1>
    <p>This endpoint is actively routing edge requests across Cloudflare Anycast CDN nodes.</p>
    <div class="status">● Edge Gateway Operational</div>
  </div>
</body>
</html>\`,
          { headers: { 'Content-Type': 'text/html; charset=utf-8' } }
        );
      }
      ` : `
      // Reverse proxy to camouflage site
      const proxyUrl = new URL(request.url);
      proxyUrl.hostname = fallbackSite;
      proxyUrl.protocol = 'https:';
      const modifiedReq = new Request(proxyUrl.toString(), {
        headers: {
          'Host': fallbackSite,
          'User-Agent': request.headers.get('User-Agent') || 'Mozilla/5.0'
        }
      });
      return await fetch(modifiedReq);
      `}

      return new Response('Edge Service Ready', { status: 200 });
    } catch (err) {
      return new Response(err.toString(), { status: 500 });
    }
  }
};

/**
 * Handles the VLESS WebSocket Stream and TCP Socket Bridge
 */
async function vlessOverWSHandler(request, targetUUID, proxyIPOverride) {
  const webSocketPair = new WebSocketPair();
  const [clientWs, serverWs] = Object.values(webSocketPair);

  serverWs.accept();

  let address = '';
  let portWithHeader = 0;
  let remoteSocket = null;
  let isVlessHeaderResolved = false;

  const earlyDataHeader = request.headers.get('sec-websocket-protocol') || '';
  const readableWebSocketStream = makeReadableWebSocketStream(serverWs, earlyDataHeader);

  readableWebSocketStream.pipeTo(new WritableStream({
    async write(chunk) {
      if (!isVlessHeaderResolved) {
        // Parse VLESS Protocol Header
        // [0]: Version (0x00)
        // [1-16]: User UUID (16 bytes)
        // [17]: Proto Addons length
        // [18 + m]: Command (0x01: TCP, 0x02: UDP, 0x03: Mux)
        // [19 + m ...]: Port & Address
        if (chunk.byteLength < 24) {
          serverWs.close(1008, 'Header too short');
          return;
        }

        const version = chunk[0];
        const clientUUIDArray = chunk.slice(1, 17);
        const clientUUID = stringifyUUID(clientUUIDArray);

        if (clientUUID.toLowerCase() !== targetUUID.toLowerCase()) {
          serverWs.close(1008, 'Invalid UUID');
          return;
        }

        const optLength = chunk[17];
        const commandIndex = 18 + optLength;
        const command = chunk[commandIndex];

        // Only TCP (0x01) supported via Cloudflare TCP Sockets
        if (command !== 1) {
          serverWs.close(1003, \`Command \${command} not supported\`);
          return;
        }

        let portIndex = commandIndex + 1;
        const port = (chunk[portIndex] << 8) | chunk[portIndex + 1];
        portWithHeader = port;

        let addressIndex = portIndex + 2;
        const addressType = chunk[addressIndex];
        let addressLength = 0;
        let addressValueIndex = addressIndex + 1;

        if (addressType === 1) {
          // IPv4
          addressLength = 4;
          address = new Uint8Array(chunk.slice(addressValueIndex, addressValueIndex + addressLength)).join('.');
        } else if (addressType === 2) {
          // Domain name
          addressLength = chunk[addressValueIndex];
          addressValueIndex += 1;
          address = new TextDecoder().decode(chunk.slice(addressValueIndex, addressValueIndex + addressLength));
        } else if (addressType === 3) {
          // IPv6
          addressLength = 16;
          const dataView = new DataView(chunk.buffer, chunk.byteOffset + addressValueIndex, addressLength);
          const ipv6 = [];
          for (let i = 0; i < 8; i++) {
            ipv6.push(dataView.getUint16(i * 2).toString(16));
          }
          address = ipv6.join(':');
        } else {
          serverWs.close(1008, \`Invalid address type \${addressType}\`);
          return;
        }

        isVlessHeaderResolved = true;
        const rawClientData = chunk.slice(addressValueIndex + addressLength);

        // Connect Outbound TCP Socket
        const targetHost = proxyIPOverride ? proxyIPOverride : address;
        try {
          remoteSocket = connect({
            hostname: targetHost,
            port: portWithHeader
          });

          // Write VLESS Response Header to Client: [0x00, 0x00] (Version 0, Addon 0)
          const vlessResponseHeader = new Uint8Array([version, 0]);
          serverWs.send(vlessResponseHeader);

          // Pipe Outbound Remote Socket to Client WebSocket
          remoteSocket.readable.pipeTo(new WritableStream({
            write(data) {
              if (serverWs.readyState === WebSocket.OPEN) {
                serverWs.send(data);
              }
            },
            close() {
              if (serverWs.readyState === WebSocket.OPEN) serverWs.close();
            },
            abort(reason) {
              if (serverWs.readyState === WebSocket.OPEN) serverWs.close(1011, reason?.toString());
            }
          })).catch(() => {});

          // If there was initial payload in the header chunk, forward it
          if (rawClientData.byteLength > 0) {
            const writer = remoteSocket.writable.getWriter();
            await writer.write(rawClientData);
            writer.releaseLock();
          }
        } catch (err) {
          serverWs.close(1011, 'Socket connection failed');
        }
      } else {
        // Forward subsequent payload from client to remote socket
        if (remoteSocket && remoteSocket.writable) {
          const writer = remoteSocket.writable.getWriter();
          await writer.write(chunk);
          writer.releaseLock();
        }
      }
    },
    close() {
      if (remoteSocket) remoteSocket.close();
    },
    abort() {
      if (remoteSocket) remoteSocket.close();
    }
  })).catch(() => {});

  return new Response(null, {
    status: 101,
    webSocket: clientWs
  });
}

/**
 * Creates a ReadableStream from client WebSocket frames
 */
function makeReadableWebSocketStream(ws, earlyDataHeader) {
  return new ReadableStream({
    start(controller) {
      ws.addEventListener('message', event => {
        controller.enqueue(new Uint8Array(event.data));
      });
      ws.addEventListener('close', () => controller.close());
      ws.addEventListener('error', err => controller.error(err));

      if (earlyDataHeader) {
        try {
          const raw = atob(earlyDataHeader.replace(/-/g, '+').replace(/_/g, '/'));
          const uint8 = new Uint8Array(raw.length);
          for (let i = 0; i < raw.length; i++) {
            uint8[i] = raw.charCodeAt(i);
          }
          controller.enqueue(uint8);
        } catch (_) {}
      }
    }
  });
}

/**
 * Formats 16-byte array into UUID string representation
 */
function stringifyUUID(arr) {
  const byteToHex = [];
  for (let i = 0; i < 256; ++i) {
    byteToHex.push((i + 0x100).toString(16).slice(1));
  }
  return [
    byteToHex[arr[0]], byteToHex[arr[1]], byteToHex[arr[2]], byteToHex[arr[3]], '-',
    byteToHex[arr[4]], byteToHex[arr[5]], '-',
    byteToHex[arr[6]], byteToHex[arr[7]], '-',
    byteToHex[arr[8]], byteToHex[arr[9]], '-',
    byteToHex[arr[10]], byteToHex[arr[11]], byteToHex[arr[12]], byteToHex[arr[13]], byteToHex[arr[14]], byteToHex[arr[15]]
  ].join('');
}
`;
}
